#pragma warning disable CS0659 // 'Vector4Byte' overrides Object.Equals(object o) but does not override Object.GetHashCode()
#pragma warning disable CS0661 // 'Vector4Byte' defines operator == or operator != but does not override Object.GetHashCode()

// Vector4Byte by mischa (based on game engine project)
using System;
using System.Runtime.CompilerServices;

namespace Mirror
{
    public struct Vector4Byte
    {
        public byte x;
        public byte y;
        public byte z;
        public byte w;

        public static readonly Vector4Byte zero = new Vector4Byte(0, 0, 0, 0);
        public static readonly Vector4Byte one = new Vector4Byte(1, 1, 1, 1);

        // constructor /////////////////////////////////////////////////////////
        public Vector4Byte(byte x, byte y, byte z, byte w)
        {
            this.x = x;
            this.y = y;
            this.z = z;
            this.w = w;
        }

        // operators ///////////////////////////////////////////////////////////
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Vector4Byte operator +(Vector4Byte a, Vector4Byte b) =>
            new Vector4Byte((byte)(a.x + b.x), (byte)(a.y + b.y), (byte)(a.z + b.z), (byte)(a.w + b.w));

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Vector4Byte operator -(Vector4Byte a, Vector4Byte b) =>
            new Vector4Byte((byte)(a.x - b.x), (byte)(a.y - b.y), (byte)(a.z - b.z), (byte)(a.w - b.w));

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Vector4Byte operator *(Vector4Byte a, byte n) =>
            new Vector4Byte((byte)(a.x * n), (byte)(a.y * n), (byte)(a.z * n), (byte)(a.w * n));

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Vector4Byte operator *(byte n, Vector4Byte a) =>
            new Vector4Byte((byte)(a.x * n), (byte)(a.y * n), (byte)(a.z * n), (byte)(a.w * n));

        // == returns true if exactly equal
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool operator ==(Vector4Byte a, Vector4Byte b) =>
            a.x == b.x &&
            a.y == b.y &&
            a.z == b.z &&
            a.w == b.w;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool operator !=(Vector4Byte a, Vector4Byte b) => !(a == b);

        // [i] component index. useful for iterating all components etc.
        public byte this[int index]
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get
            {
                switch (index)
                {
                    case 0: return x;
                    case 1: return y;
                    case 2: return z;
                    case 3: return w;
                    default: throw new IndexOutOfRangeException($"Vector4Byte[{index}] out of range.");
                }
            }
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            set
            {
                switch (index)
                {
                    case 0:
                        x = value;
                        break;
                    case 1:
                        y = value;
                        break;
                    case 2:
                        z = value;
                        break;
                    case 3:
                        w = value;
                        break;
                    default: throw new IndexOutOfRangeException($"Vector4Byte[{index}] out of range.");
                }
            }
        }

        // instance functions //////////////////////////////////////////////////
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public override string ToString() => $"({x} {y} {z} {w})";

        // equality ////////////////////////////////////////////////////////////
        // implement Equals & HashCode explicitly for performance.
        // calling .Equals (instead of "==") checks for exact equality.
        // (API compatibility)
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public bool Equals(Vector4Byte other) =>
            x == other.x && y == other.y && z == other.z && w == other.w;

        // Equals(object) can reuse Equals(Vector4Byte)
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public override bool Equals(object other) =>
            other is Vector4Byte vector4 && Equals(vector4);

#if UNITY_2021_3_OR_NEWER
        // Unity 2019/2020 don't have HashCode.Combine yet.
        // this is only to avoid reflection. without defining, it works too.
        // default generated by rider
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public override int GetHashCode() => HashCode.Combine(x, y, z, w);
#endif
    }
}