#pragma warning disable CS0659 // 'Vector2Byte' overrides Object.Equals(object o) but does not override Object.GetHashCode()
#pragma warning disable CS0661 // 'Vector2Byte' defines operator == or operator != but does not override Object.GetHashCode()

// Vector2Byte by mischa (based on game engine project)
using System;
using System.Runtime.CompilerServices;

namespace Mirror
{
    public struct Vector2Byte
    {
        public byte x;
        public byte y;

        public static readonly Vector2Byte zero = new Vector2Byte(0, 0);
        public static readonly Vector2Byte one = new Vector2Byte(1, 1);
        public static readonly Vector2Byte left = new Vector2Byte(0, 1);
        public static readonly Vector2Byte right = new Vector2Byte(1, 0);
        public static readonly Vector2Byte up = new Vector2Byte(0, 1);
        public static readonly Vector2Byte down = new Vector2Byte(0, 0);

        // constructor /////////////////////////////////////////////////////////
        public Vector2Byte(byte x, byte y)
        {
            this.x = x;
            this.y = y;
        }

        // operators ///////////////////////////////////////////////////////////
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Vector2Byte operator +(Vector2Byte a, Vector2Byte b) =>
            new Vector2Byte((byte)(a.x + b.x), (byte)(a.y + b.y));

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Vector2Byte operator -(Vector2Byte a, Vector2Byte b) =>
            new Vector2Byte((byte)(a.x - b.x), (byte)(a.y - b.y));

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Vector2Byte operator *(Vector2Byte a, byte n) =>
            new Vector2Byte((byte)(a.x * n), (byte)(a.y * n));

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Vector2Byte operator *(byte n, Vector2Byte a) =>
            new Vector2Byte((byte)(a.x * n), (byte)(a.y * n));

        // == returns true if exactly equal
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool operator ==(Vector2Byte a, Vector2Byte b) =>
            a.x == b.x && a.y == b.y;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool operator !=(Vector2Byte a, Vector2Byte b) => !(a == b);

        // [i] component index. useful for iterating all components etc.
        public byte this[int index]
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get
            {
                switch (index)
                {
                    case 0: return x;
                    case 1: return y;
                    default: throw new IndexOutOfRangeException($"Vector2Byte[{index}] out of range.");
                }
            }
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            set
            {
                switch (index)
                {
                    case 0:
                        x = value;
                        break;
                    case 1:
                        y = value;
                        break;
                    default: throw new IndexOutOfRangeException($"Vector2Byte[{index}] out of range.");
                }
            }
        }

        // instance functions //////////////////////////////////////////////////
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public override string ToString() => $"({x} {y})";

        // equality ////////////////////////////////////////////////////////////
        // implement Equals & HashCode explicitly for performance.
        // calling .Equals (instead of "==") checks for exact equality.
        // (API compatibility)
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public bool Equals(Vector2Byte other) =>
            x == other.x && y == other.y;

        // Equals(object) can reuse Equals(Vector2Byte)
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public override bool Equals(object other) =>
            other is Vector2Byte vector2 && Equals(vector2);

#if UNITY_2021_3_OR_NEWER
        // Unity 2019/2020 don't have HashCode.Combine yet.
        // this is only to avoid reflection. without defining, it works too.
        // default generated by rider
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public override int GetHashCode() => HashCode.Combine(x, y);
#endif
    }
}