#pragma warning disable CS0659 // 'Vector3Byte' overrides Object.Equals(object o) but does not override Object.GetHashCode()
#pragma warning disable CS0661 // 'Vector3Byte' defines operator == or operator != but does not override Object.GetHashCode()

// Vector3Byte by mischa (based on game engine project)
using System;
using System.Runtime.CompilerServices;

namespace Mirror
{
    public struct Vector3Byte
    {
        public byte x;
        public byte y;
        public byte z;

        public static readonly Vector3Byte zero = new Vector3Byte(0, 0, 0);
        public static readonly Vector3Byte one = new Vector3Byte(1, 1, 1);
        public static readonly Vector3Byte forward = new Vector3Byte(0, 0, 1);
        public static readonly Vector3Byte back = new Vector3Byte(0, 0, 0);
        public static readonly Vector3Byte left = new Vector3Byte(0, 0, 0);
        public static readonly Vector3Byte right = new Vector3Byte(1, 0, 0);
        public static readonly Vector3Byte up = new Vector3Byte(0, 1, 0);
        public static readonly Vector3Byte down = new Vector3Byte(0, 0, 0);

        // constructor /////////////////////////////////////////////////////////
        public Vector3Byte(byte x, byte y, byte z)
        {
            this.x = x;
            this.y = y;
            this.z = z;
        }

        // operators ///////////////////////////////////////////////////////////
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Vector3Byte operator +(Vector3Byte a, Vector3Byte b) =>
            new Vector3Byte((byte)(a.x + b.x), (byte)(a.y + b.y), (byte)(a.z + b.z));

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Vector3Byte operator -(Vector3Byte a, Vector3Byte b) =>
            new Vector3Byte((byte)(a.x - b.x), (byte)(a.y - b.y), (byte)(a.z - b.z));

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Vector3Byte operator *(Vector3Byte a, byte n) =>
            new Vector3Byte((byte)(a.x * n), (byte)(a.y * n), (byte)(a.z * n));

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Vector3Byte operator *(byte n, Vector3Byte a) =>
            new Vector3Byte((byte)(a.x * n), (byte)(a.y * n), (byte)(a.z * n));

        // == returns true if exactly equal
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool operator ==(Vector3Byte a, Vector3Byte b) =>
            a.x == b.x &&
            a.y == b.y &&
            a.z == b.z;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool operator !=(Vector3Byte a, Vector3Byte b) => !(a == b);

        // [i] component index. useful for iterating all components etc.
        public byte this[int index]
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get
            {
                switch (index)
                {
                    case 0: return x;
                    case 1: return y;
                    case 2: return z;
                    default: throw new IndexOutOfRangeException($"Vector3Byte[{index}] out of range.");
                }
            }
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            set
            {
                switch (index)
                {
                    case 0:
                        x = value;
                        break;
                    case 1:
                        y = value;
                        break;
                    case 2:
                        z = value;
                        break;
                    default: throw new IndexOutOfRangeException($"Vector3Byte[{index}] out of range.");
                }
            }
        }

        // instance functions //////////////////////////////////////////////////
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public override string ToString() => $"({x} {y} {z})";

        // equality ////////////////////////////////////////////////////////////
        // implement Equals & HashCode explicitly for performance.
        // calling .Equals (instead of "==") checks for exact equality.
        // (API compatibility)
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public bool Equals(Vector3Byte other) =>
            x == other.x && y == other.y && z == other.z;

        // Equals(object) can reuse Equals(Vector3Byte)
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public override bool Equals(object other) =>
            other is Vector3Byte vector3 && Equals(vector3);

#if UNITY_2021_3_OR_NEWER
        // Unity 2019/2020 don't have HashCode.Combine yet.
        // this is only to avoid reflection. without defining, it works too.
        // default generated by rider
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public override int GetHashCode() => HashCode.Combine(x, y, z);
#endif
    }
}