#pragma warning disable CS0659 // 'Vector2SByte' overrides Object.Equals(object o) but does not override Object.GetHashCode()
#pragma warning disable CS0661 // 'Vector2SByte' defines operator == or operator != but does not override Object.GetHashCode()

// Vector2SByte by mischa (based on game engine project)
using System;
using System.Runtime.CompilerServices;

namespace Mirror
{
    public struct Vector2SByte
    {
        public sbyte x;
        public sbyte y;

        public static readonly Vector2SByte zero = new Vector2SByte(0, 0);
        public static readonly Vector2SByte one = new Vector2SByte(1, 1);
        public static readonly Vector2SByte left = new Vector2SByte(-1, 0);
        public static readonly Vector2SByte right = new Vector2SByte(1, 0);
        public static readonly Vector2SByte up = new Vector2SByte(0, 1);
        public static readonly Vector2SByte down = new Vector2SByte(0, -1);

        // constructor /////////////////////////////////////////////////////////
        public Vector2SByte(sbyte x, sbyte y)
        {
            this.x = x;
            this.y = y;
        }

        // operators ///////////////////////////////////////////////////////////
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Vector2SByte operator +(Vector2SByte a, Vector2SByte b) =>
            new Vector2SByte((sbyte)(a.x + b.x), (sbyte)(a.y + b.y));

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Vector2SByte operator -(Vector2SByte a, Vector2SByte b) =>
            new Vector2SByte((sbyte)(a.x - b.x), (sbyte)(a.y - b.y));

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Vector2SByte operator -(Vector2SByte v) =>
            new Vector2SByte((sbyte)-v.x, (sbyte)-v.y);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Vector2SByte operator *(Vector2SByte a, sbyte n) =>
            new Vector2SByte((sbyte)(a.x * n), (sbyte)(a.y * n));

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Vector2SByte operator *(sbyte n, Vector2SByte a) =>
            new Vector2SByte((sbyte)(a.x * n), (sbyte)(a.y * n));

        // == returns true if exactly equal
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool operator ==(Vector2SByte a, Vector2SByte b) =>
            a.x == b.x && a.y == b.y;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool operator !=(Vector2SByte a, Vector2SByte b) => !(a == b);

        // [i] component index. useful for iterating all components etc.
        public sbyte this[int index]
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get
            {
                switch (index)
                {
                    case 0: return x;
                    case 1: return y;
                    default: throw new IndexOutOfRangeException($"Vector2SByte[{index}] out of range.");
                }
            }
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            set
            {
                switch (index)
                {
                    case 0:
                        x = value;
                        break;
                    case 1:
                        y = value;
                        break;
                    default: throw new IndexOutOfRangeException($"Vector2SByte[{index}] out of range.");
                }
            }
        }

        // instance functions //////////////////////////////////////////////////
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public override string ToString() => $"({x} {y})";

        // equality ////////////////////////////////////////////////////////////
        // implement Equals & HashCode explicitly for performance.
        // calling .Equals (instead of "==") checks for exact equality.
        // (API compatibility)
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public bool Equals(Vector2SByte other) =>
            x == other.x && y == other.y;

        // Equals(object) can reuse Equals(Vector2SByte)
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public override bool Equals(object other) =>
            other is Vector2SByte vector2 && Equals(vector2);

#if UNITY_2021_3_OR_NEWER
        // Unity 2019/2020 don't have HashCode.Combine yet.
        // this is only to avoid reflection. without defining, it works too.
        // default generated by rider
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public override int GetHashCode() => HashCode.Combine(x, y);
#endif
    }
}