coverage:
  status:
    project:
      default:
        target: auto      # Maintain current coverage
        threshold: 1%     # Allow 1% drop
    patch:
      default:
        target: 90%       # New code should be 70% covered

ignore:
  - "Assets/Mirror/Examples/**"
  - "Assets/Mirror/Hosting/**"
  - "Assets/Mirror/Plugins/**"
  - "Assets/Mirror/Tests/**"
  - "Assets/Mirror/Transports/Edgegap/**"

comment:
  layout: "diff, flags, files"
  behavior: default
  require_changes: false
  
flags:
  unittests:
    paths:
      - Assets/Mirror/