{
    "plugins": [
      ["@semantic-release/commit-analyzer", {
        "preset": "angular",
        "releaseRules": [
          {"type": "breaking", "release": "major"},
          {"type": "feature", "release": "minor"},
        ]
      }],
      '@semantic-release/release-notes-generator', 
      ["@semantic-release/github", {
      "assets": [
        {"path": "Mirror.unitypackage", "label": "Mirror.unitypackage"}
      ]
    }],
    ]
}