{
    verifyConditions: ["@semantic-release/github"],
    prepare: [
        {
            "path": "@semantic-release/exec",
            "prepareCmd": "echo ${nextRelease.version} > Assets/Mirror/version.txt"
        }
    ],
    publish: [        
        {
            "path": "@semantic-release/github",
            "assets": [
                {"path": "Mirror.unitypackage", "label": "Mirror Unity Package", "name": "Mirror-${nextRelease.version}.unitypackage"}
            ]
        }
    ],
    "plugins": [
        ["@semantic-release/commit-analyzer", {
            "preset": "angular",
            "releaseRules": [
                {"type": "breaking", "release": "major"},
                {"type": "feature", "release": "minor"},
            ]
        }],
        ['@semantic-release/release-notes-generator', {
          "preset": "angular",
            "releaseRules": [
                {"type": "breaking", "release": "major"},
                {"type": "feature", "release": "minor"},
            ]
        }],
    ]
}
