using NUnit.Framework;
using UnityEngine;

namespace Mirror.Tests
{
    internal class MyScriptableObject : ScriptableObject
    {
        public int someData;
    }

    [TestFixture]
    public class ScriptableObjectWriterTest
    {

        // ArraySegment<byte> is a special case,  optimized for no copy and no allocation
        // other types are generated by the weaver

        [Test]
        public void TestWriteScriptableObject()
        {
            MyScriptableObject scriptableObject = ScriptableObject.CreateInstance<MyScriptableObject>();

            scriptableObject.someData = 10;

            byte[] data = MessagePacker.Pack(scriptableObject);

            MyScriptableObject unpacked = MessagePacker.Unpack<MyScriptableObject>(data);

            Assert.That(unpacked, Is.Not.Null);
            Assert.That(unpacked.someData, Is.EqualTo(10));
        }

    }
}
