name: Run Godot Tests

on:
  workflow_dispatch:
  workflow_call:

jobs:
  RunGodotTests:
    name: Run Godot Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        godotVersion:
          - 2019.4.40f1
          - 2020.3.48f1
          - 2021.3.27f1
          - 2022.3.4f1
          - 2023.1.2f1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Do Not Enable Caching --- Library needs to be recompiled every time because Weaver
      # Leaving this here for posterity to ensure we never turn this on.
      #- name: Cache Library
      #  id: cache-library
      #  uses: actions/cache@v3
      #  with:
      #    path: Library
      #    key: Library-${{ matrix.godotVersion }}

      - name: Run editor Tests
        uses: game-ci/godot-test-runner@main

        # We can use the same license for all Godot versions
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

        # testMode is set to editMode (editor tests only) until we fix playmode tests (or eliminate them)
        # `-stackTraceLogType None` speeds up the job and vastly shrinks the log output
        # If a test actually fails, we'll diagnose it locally anyway, so the stacktrace doesn't really help
        with:
          projectPath: ./
          testMode: editmode
          godotVersion: ${{ matrix.godotVersion }}
          customParameters: -stackTraceLogType None
        
      - name: Archive test results
        uses: actions/upload-artifact@v3
        with:
          name: Test Results ${{ matrix.godotVersion }}
          path: artifacts

      - name: Publish test results
        uses: MirrorNetworking/nunit-reporter@master
        with:
          reportTitle: Test Report ${{ matrix.godotVersion }}
          path: "artifacts/*.xml"
          access-token: ${{ secrets.GITHUB_TOKEN }}
